-- MySQL Script generated by MySQL Workbench
-- mié 01 ago 2018 17:54:20 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rveloz
-- -----------------------------------------------------
-- Base de Datos Para el Sistema de Reporteria de Recarga Veloz

-- -----------------------------------------------------
-- Schema rveloz
--
-- Base de Datos Para el Sistema de Reporteria de Recarga Veloz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rveloz` DEFAULT CHARACTER SET utf8 ;
USE `rveloz` ;

-- -----------------------------------------------------
-- Table `rveloz`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rveloz`.`usuario` (
  `usuariocod` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `usuarioemail` VARCHAR(80) NULL,
  `usuarionom` VARCHAR(80) NULL,
  `usuariopswd` VARCHAR(128) NULL,
  `usuariofching` DATETIME NULL,
  `usuariopswdest` CHAR(3) NULL,
  `usuariopswdexp` DATETIME NULL,
  `usuarioest` CHAR(3) NULL,
  `usuarioactcod` VARCHAR(128) NULL,
  `usuariopswdchg` VARCHAR(128) NULL,
  `usuariotipo` CHAR(3) NULL COMMENT 'Tipo de Usuario, Normal, Consultor o Cliente',
  PRIMARY KEY (`usuariocod`),
  UNIQUE INDEX `usuarioemail_UNIQUE` (`usuarioemail` ASC),
  INDEX `usuariotipo` (`usuariotipo` ASC, `usuarioemail` ASC, `usuariocod` ASC, `usuarioest` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rveloz`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rveloz`.`roles` (
  `rolescod` VARCHAR(15) NOT NULL,
  `rolesdsc` VARCHAR(45) NULL,
  `rolesest` CHAR(3) NULL,
  PRIMARY KEY (`rolescod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rveloz`.`roles_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rveloz`.`roles_usuarios` (
  `usuariocod` BIGINT(10) NOT NULL,
  `rolescod` VARCHAR(15) NOT NULL,
  `roleusuarioest` CHAR(3) NULL,
  `roleusuariofch` DATETIME NULL,
  `roleusuarioexp` DATETIME NULL,
  PRIMARY KEY (`usuariocod`, `rolescod`),
  INDEX `rol_usuario_key_idx` (`rolescod` ASC),
  CONSTRAINT `usuario_rol_key`
    FOREIGN KEY (`usuariocod`)
    REFERENCES `rveloz`.`usuario` (`usuariocod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rol_usuario_key`
    FOREIGN KEY (`rolescod`)
    REFERENCES `rveloz`.`roles` (`rolescod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rveloz`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rveloz`.`bitacora` (
  `bitacoracod` INT NOT NULL AUTO_INCREMENT,
  `bitacorafch` DATETIME NULL,
  `bitprograma` VARCHAR(15) NULL,
  `bitdescripcion` VARCHAR(255) NULL,
  `bitobservacion` MEDIUMTEXT NULL,
  `bitTipo` CHAR(3) NULL,
  `bitusuario` BIGINT(18) NULL,
  PRIMARY KEY (`bitacoracod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
